project:
  type: website
  output-dir: docs
  render:
    - mca.qmd

website:
  title: "R Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - mca.qmd
    tools:
      - icon: github
        href: https://github.com/CasHsmn/R_comb_habit
format:
  html:
    theme: cosmo
    toc: true




