project:
  type: website
  output-dir: docs

website:
  title: "R Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - prelim_output.qmd

format:
  html:
    theme: cosmo
    toc: true




