project:
  type: website
  output-dir: docs

website:
  title: "R Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - prelim_output.qmd
    tools:
      - icon: github
        href: https://github.com/CasHsmn/R_comb_habit
format:
  html:
    theme: cosmo
    toc: true




